approvedGitRepositories:
  - "**"

enableGlobalCache: true

enableScripts: true

#nodeLinker: pnp

nodeLinker: node-modules
nmMode: hardlinks-global

# x64 と arm64 の両方を 1 台でビルドするため
supportedArchitectures:
  os:
    - current
  cpu:
    - x64
    - arm64
  libc:
    - current
