import os from 'os';
import path from 'path';

// アプリケーションのディレクトリ名
export const APP_DIR_NAME = '.kura_toolkit';

// ホームディレクトリを取得
export function getHomeDir(): string {
    return os.homedir();
}

// アプリルートディレクトリを取得
export function getAppRootDir(): string {
    return path.join(getHomeDir(), APP_DIR_NAME);
}

// IPCチャンネル定義
export const IPC_CHANNELS = {
    APP_GET_INFO: 'app:getInfo',
    APP_SET_THEME: 'app:setTheme',
    APP_SET_LANGUAGE: 'app:setLanguage',
    APP_QUIT: 'app:quit',
    WINDOW_MINIMIZE: 'window:minimize',
    WINDOW_MAXIMIZE_OR_RESTORE: 'window:maximizeOrRestore',
    WINDOW_CLOSE: 'window:close',
    // 閉じる前の確認 (main -> renderer の問い合わせと、renderer からの閉じてよいという返事)
    WINDOW_CLOSE_REQUESTED: 'window:closeRequested',
    WINDOW_CONFIRM_CLOSE: 'window:confirmClose',
    WINDOW_IS_MAXIMIZED: 'window:isMaximized',
    MAIN_CONSOLE: 'main:console',
    UPDATER_CHECK: 'updater:check',
    UPDATER_DOWNLOAD: 'updater:download',
    UPDATER_QUIT_AND_INSTALL: 'updater:quitAndInstall',
    UPDATER_GET_STATE: 'updater:getState',
    UPDATER_STATE_CHANGED: 'updater:stateChanged',
    SETTINGS_GET: 'settings:get',
    SETTINGS_UPDATE: 'settings:update',
    SETTINGS_GET_LOAD_ERROR: 'settings:getLoadError',
    SETTINGS_RESET_BROKEN: 'settings:resetBroken',
    STORAGE_GET_INFO: 'storage:getInfo',
    STORAGE_MOVE: 'storage:move',
    STORAGE_SET_WORK_DIR: 'storage:setWorkDir',
    STORAGE_CLEANUP_WORK: 'storage:cleanupWork',
    STORAGE_PLAN_MOVE: 'storage:planMove',
    FFMPEG_DETECT: 'ffmpeg:detect',
    DIALOG_OPEN_FILES: 'dialog:openFiles',
    DIALOG_OPEN_DIRECTORY: 'dialog:openDirectory',
    DIALOG_SAVE_FILE: 'dialog:saveFile',
    FILES_COLLECT: 'files:collect',
    JOB_CANCEL: 'job:cancel',
    JOB_EVENT: 'job:event',
    AUDIO_ANALYZE: 'audio:analyze',
    AUDIO_NORMALIZE: 'audio:normalize',
    AUDIO_CHECK_OUTPUTS: 'audio:checkOutputs',
    AUDIO_FORMATS: 'audio:formats',
    AUDIO_PROBE: 'audio:probe',
    CHAPTER_PROBE: 'chapter:probe',
    CHAPTER_CUT: 'chapter:cut',
    CHAPTER_SPLIT: 'chapter:split',
    CHAPTER_CHECK_CUT: 'chapter:checkCut',
    CHAPTER_CHECK_SPLIT: 'chapter:checkSplit',
    VECTORIZER_LOAD_IMAGE: 'vectorizer:loadImage',
    VECTORIZER_CONVERT: 'vectorizer:convert',
    VECTORIZER_SAVE_SVG: 'vectorizer:saveSvg',
    CLEANUP_GET_ROOTS: 'cleanup:getRoots',
    CLEANUP_GET_CAPABILITIES: 'cleanup:getCapabilities',
    CLEANUP_OPEN_PERMISSION_SETTINGS: 'cleanup:openPermissionSettings',
    CLEANUP_SCAN: 'cleanup:scan',
    CLEANUP_REMOVE: 'cleanup:remove',
    VOICE_LIBRARY_STATUS: 'voice:library:status',
    VOICE_LIBRARY_REFRESH_PLATFORM: 'voice:library:refreshPlatform',
    VOICE_LIBRARY_CHECK_FEATURE: 'voice:library:checkFeature',
    VOICE_LIBRARY_DOWNLOAD: 'voice:library:download',
    VOICE_LIBRARY_REMOVE: 'voice:library:remove',
    VOICE_LIBRARY_ENSURE_SEPARATOR_LIST: 'voice:library:ensureSeparatorList',
    VOICE_LIBRARY_PROBE_SIZES: 'voice:library:probeSizes',
    VOICE_LIBRARY_PENDING_UPDATES: 'voice:library:pendingUpdates',
    VOICE_LIBRARY_MARK_PROMPTED: 'voice:library:markPrompted',
    VOICE_OPEN_EXTERNAL: 'voice:openExternal',
    VOICE_SET_FEATURE: 'voice:setFeature',
    VOICE_REQUEST_MICROPHONE: 'voice:requestMicrophone',
    VOICE_RECORDING_BEGIN: 'voice:recording:begin',
    VOICE_RECORDING_APPEND: 'voice:recording:append',
    VOICE_RECORDING_FINISH: 'voice:recording:finish',
    VOICE_RECORDING_DISCARD: 'voice:recording:discard',
    VOICE_MEDIA_PREPARE: 'voice:media:prepare',
    VOICE_MEDIA_MIX: 'voice:media:mix',
    VOICE_MEDIA_DISCARD: 'voice:media:discard',
    VOICE_MEDIA_DISCARD_WORK: 'voice:media:discardWork',
    VOICE_MEDIA_REF: 'voice:media:ref',
    VOICE_MEDIA_WAVEFORM: 'voice:media:waveform',
    VOICE_SEPARATION_MODELS: 'voice:separation:models',
    VOICE_SEPARATION_RUN: 'voice:separation:run',
    VOICE_CONVERSION_RUN: 'voice:conversion:run',
    VOICE_CONVERSION_MIX: 'voice:conversion:mix',
    VOICE_CONVERSION_FILTER: 'voice:conversion:filter',
    VOICE_RUBBERBAND: 'voice:rubberband',
    VOICE_TTS_RUN: 'voice:tts:run',
    VOICE_TTS_CANCEL_CONFIRMATION: 'voice:tts:cancelConfirmation',
    VOICE_TTS_LOAD_TEXT: 'voice:tts:loadText',
    VOICE_TTS_SAVE_TEXT: 'voice:tts:saveText',
    VOICE_MODELS_LIST: 'voice:models:list',
    VOICE_MODELS_RENAME: 'voice:models:rename',
    VOICE_MODELS_SET_LANGUAGES: 'voice:models:setLanguages',
    VOICE_MODELS_REMOVE: 'voice:models:remove',
    VOICE_MODELS_EXPORT: 'voice:models:export',
    VOICE_MODELS_INSPECT_IMPORT: 'voice:models:inspectImport',
    VOICE_MODELS_COMMIT_IMPORT: 'voice:models:commitImport',
    VOICE_MODELS_CANCEL_IMPORT: 'voice:models:cancelImport',
    VOICE_MODELS_CHOOSE_IMPORT_FILES: 'voice:models:chooseImportFiles',
    VOICE_MODELS_OPEN_HUB: 'voice:models:openHub',
    VOICE_PRESETS_LIST: 'voice:presets:list',
    VOICE_PRESETS_SAVE: 'voice:presets:save',
    VOICE_PRESETS_RENAME: 'voice:presets:rename',
    VOICE_PRESETS_REMOVE: 'voice:presets:remove',
    VOICE_TRAINING_SETS_LIST: 'voice:trainingSets:list',
    VOICE_TRAINING_SETS_GET: 'voice:trainingSets:get',
    VOICE_TRAINING_SETS_CREATE: 'voice:trainingSets:create',
    VOICE_TRAINING_SETS_RENAME: 'voice:trainingSets:rename',
    VOICE_TRAINING_SETS_REMOVE: 'voice:trainingSets:remove',
    VOICE_TRAINING_SETS_ADD_RECORDING: 'voice:trainingSets:addRecording',
    VOICE_TRAINING_SETS_ADD_FILES: 'voice:trainingSets:addFiles',
    VOICE_TRAINING_SETS_REMOVE_AUDIO: 'voice:trainingSets:removeAudio',
    VOICE_TRAINING_SETS_ADD_GROUP: 'voice:trainingSets:addGroup',
    VOICE_TRAINING_SETS_SET_GROUP_TEXT: 'voice:trainingSets:setGroupText',
    VOICE_TRAINING_SETS_REMOVE_GROUP: 'voice:trainingSets:removeGroup',
    VOICE_TRAINING_SETS_FILTER_AUDIO: 'voice:trainingSets:filterAudio',
    VOICE_TRAINING_SETS_REPLACE_AUDIO: 'voice:trainingSets:replaceAudio',
    VOICE_TRAINING_SETS_FILTER_ALL: 'voice:trainingSets:filterAll',
    VOICE_TRAINING_SETS_SILENCE: 'voice:trainingSets:silence',
    VOICE_TRAINING_RVC_START: 'voice:training:rvcStart',
    VOICE_TRAINING_TTS_START: 'voice:training:ttsStart',
    VOICE_EXPORT_RUN: 'voice:export:run',
    VOICE_EXPORT_EXISTING: 'voice:export:existing',
} as const;
