import { SEPARATOR_MODEL_PREFIX } from '@shared/voice/requirements';
import type { LibraryItem, SeparationArch } from '@shared/voice/types';

// 分離モデルの概要 (ダウンロードの画面と分離の画面に示す)。モデルのファイル名 -> 概要の翻訳キー
// (voice.library.separatorModelNotes.<キー>)。同じ系統のモデルは同じ概要を共有する。
// 分離のパッケージ一式 (audio-separator) の版を上げたら、一覧に増えたモデルの概要を足す
export const SEPARATOR_MODEL_NOTES: Record<string, string> = {
    '10_SP-UVR-2B-32000-1.pth': 'vrSp',
    '11_SP-UVR-2B-32000-2.pth': 'vrSp',
    '12_SP-UVR-3B-44100.pth': 'vrSp',
    '13_SP-UVR-4B-44100-1.pth': 'vrSp',
    '14_SP-UVR-4B-44100-2.pth': 'vrSp',
    '15_SP-UVR-MID-44100-1.pth': 'vrSp',
    '16_SP-UVR-MID-44100-2.pth': 'vrSp',
    '17_HP-Wind_Inst-UVR.pth': 'vrWind',
    '1_HP-UVR.pth': 'vrHp',
    '2_HP-UVR.pth': 'vrHp',
    '3_HP-Vocal-UVR.pth': 'vrHpVocal',
    '4_HP-Vocal-UVR.pth': 'vrHpVocal',
    '5_HP-Karaoke-UVR.pth': 'vrKaraoke',
    '6_HP-Karaoke-UVR.pth': 'vrKaraoke',
    '7_HP2-UVR.pth': 'vrHp2',
    '8_HP2-UVR.pth': 'vrHp2',
    '9_HP2-UVR.pth': 'vrHp2',
    'aspiration_mel_band_roformer_less_aggr_sdr_18.1201.ckpt': 'aspiration',
    'aspiration_mel_band_roformer_sdr_18.9845.ckpt': 'aspiration',
    'BS-Roformer-SW.ckpt': 'bsRoformerSw',
    'bs_roformer_instrumental_resurrection_gabox.ckpt': 'resurrectionInstGabox',
    'bs_roformer_instrumental_resurrection_unwa.ckpt': 'resurrectionInst',
    'bs_roformer_karaoke_anvuew.ckpt': 'roformerKaraoke',
    'bs_roformer_karaoke_frazer_becruily.ckpt': 'roformerKaraoke',
    'bs_roformer_male_female_by_aufr33_sdr_7.2889.ckpt': 'maleFemale',
    'bs_roformer_vocals_gabox.ckpt': 'gaboxBsVocals',
    'bs_roformer_vocals_resurrection_unwa.ckpt': 'resurrectionVocals',
    'bs_roformer_vocals_revive_unwa.ckpt': 'revive',
    'bs_roformer_vocals_revive_v2_unwa.ckpt': 'reviveV2',
    'bs_roformer_vocals_revive_v3e_unwa.ckpt': 'reviveV3e',
    'denoise_mel_band_roformer_aufr33_aggr_sdr_27.9768.ckpt': 'melDenoiseAggressive',
    'denoise_mel_band_roformer_aufr33_sdr_27.9959.ckpt': 'melDenoise',
    'dereverb-echo_mel_band_roformer_sdr_10.0169.ckpt': 'sucialDeReverbEcho',
    'dereverb-echo_mel_band_roformer_sdr_13.4843_v2.ckpt': 'sucialDeReverbEcho',
    'dereverb_big_mbr_ep_362.ckpt': 'sucialDeReverbBig',
    'dereverb_echo_mbr_fused.ckpt': 'sucialDeReverbEchoFused',
    'dereverb_mel_band_roformer_anvuew_sdr_19.1729.ckpt': 'anvuewDeReverb',
    'dereverb_mel_band_roformer_less_aggressive_anvuew_sdr_18.8050.ckpt': 'anvuewDeReverbLess',
    'dereverb_mel_band_roformer_mono_anvuew.ckpt': 'anvuewDeReverbMono',
    'dereverb_super_big_mbr_ep_346.ckpt': 'sucialDeReverbBig',
    'deverb_bs_roformer_8_384dim_10depth.ckpt': 'bsDeReverb',
    'hdemucs_mmi.yaml': 'demucsMmi',
    'htdemucs.yaml': 'demucs',
    'htdemucs_6s.yaml': 'demucs6s',
    'htdemucs_ft.yaml': 'demucsFt',
    'Kim_Inst.onnx': 'mdxKimInst',
    'Kim_Vocal_1.onnx': 'mdxKimVocal',
    'Kim_Vocal_2.onnx': 'mdxKimVocal',
    'kuielab_a_bass.onnx': 'kuielabBass',
    'kuielab_a_drums.onnx': 'kuielabDrums',
    'kuielab_a_other.onnx': 'kuielabOther',
    'kuielab_a_vocals.onnx': 'kuielabVocals',
    'kuielab_b_bass.onnx': 'kuielabBass',
    'kuielab_b_drums.onnx': 'kuielabDrums',
    'kuielab_b_other.onnx': 'kuielabOther',
    'kuielab_b_vocals.onnx': 'kuielabVocals',
    'MDX23C-8KFFT-InstVoc_HQ.ckpt': 'mdx23cInstVoc',
    'MDX23C-De-Reverb-aufr33-jarredou.ckpt': 'mdx23cDeReverb',
    'MDX23C-DrumSep-aufr33-jarredou.ckpt': 'drumSep',
    'mel_band_roformer_bleed_suppressor_v1.ckpt': 'bleedSuppressor',
    'mel_band_roformer_crowd_aufr33_viperx_sdr_8.7144.ckpt': 'crowd',
    'mel_band_roformer_denoise_debleed_gabox.ckpt': 'denoiseDebleed',
    'mel_band_roformer_instrumental_2_gabox.ckpt': 'gaboxInst',
    'mel_band_roformer_instrumental_3_gabox.ckpt': 'gaboxInst',
    'mel_band_roformer_instrumental_becruily.ckpt': 'becruilyInst',
    'mel_band_roformer_instrumental_bleedless_v1_gabox.ckpt': 'gaboxInstBleedless',
    'mel_band_roformer_instrumental_bleedless_v2_gabox.ckpt': 'gaboxInstBleedless',
    'mel_band_roformer_instrumental_bleedless_v3_gabox.ckpt': 'gaboxInstBleedless',
    'mel_band_roformer_instrumental_fullness_noise_v4_gabox.ckpt': 'gaboxInstFullnessNoisy',
    'mel_band_roformer_instrumental_fullness_v1_gabox.ckpt': 'gaboxInstFullness',
    'mel_band_roformer_instrumental_fullness_v2_gabox.ckpt': 'gaboxInstFullness',
    'mel_band_roformer_instrumental_fullness_v3_gabox.ckpt': 'gaboxInstFullness',
    'mel_band_roformer_instrumental_fullness_v4_gabox.ckpt': 'gaboxInstFullness',
    'mel_band_roformer_instrumental_fv7z_gabox.ckpt': 'gaboxInstFv7z',
    'mel_band_roformer_instrumental_fv8_gabox.ckpt': 'gaboxInstFv',
    'mel_band_roformer_instrumental_fv8b_gabox.ckpt': 'gaboxInstFv',
    'mel_band_roformer_instrumental_fvx_gabox.ckpt': 'gaboxInstFv',
    'mel_band_roformer_instrumental_gabox.ckpt': 'gaboxInst',
    'mel_band_roformer_instrumental_instv5_gabox.ckpt': 'gaboxInstV',
    'mel_band_roformer_instrumental_instv5n_gabox.ckpt': 'gaboxInstVN',
    'mel_band_roformer_instrumental_instv6_gabox.ckpt': 'gaboxInstV',
    'mel_band_roformer_instrumental_instv6n_gabox.ckpt': 'gaboxInstVN',
    'mel_band_roformer_instrumental_instv7_gabox.ckpt': 'gaboxInstV',
    'mel_band_roformer_instrumental_instv7n_gabox.ckpt': 'gaboxInstVN',
    'mel_band_roformer_instrumental_instv8_gabox.ckpt': 'gaboxInstV',
    'mel_band_roformer_instrumental_instv8n_gabox.ckpt': 'gaboxInstVN',
    'mel_band_roformer_karaoke_aufr33_viperx_sdr_10.1956.ckpt': 'roformerKaraoke',
    'mel_band_roformer_karaoke_becruily.ckpt': 'roformerKaraoke',
    'mel_band_roformer_karaoke_gabox.ckpt': 'roformerKaraoke',
    'mel_band_roformer_karaoke_gabox_v2.ckpt': 'roformerKaraoke',
    'mel_band_roformer_kim_ft2_bleedless_unwa.ckpt': 'kimFtBleedless',
    'mel_band_roformer_kim_ft2_unwa.ckpt': 'kimFt',
    'mel_band_roformer_kim_ft3_unwa.ckpt': 'kimFt',
    'mel_band_roformer_kim_ft_unwa.ckpt': 'kimFt',
    'mel_band_roformer_vocal_fullness_aname.ckpt': 'vocalFullness',
    'mel_band_roformer_vocals_becruily.ckpt': 'becruilyVocals',
    'mel_band_roformer_vocals_fv1_gabox.ckpt': 'gaboxVocalsFv',
    'mel_band_roformer_vocals_fv2_gabox.ckpt': 'gaboxVocalsFv',
    'mel_band_roformer_vocals_fv3_gabox.ckpt': 'gaboxVocalsFv',
    'mel_band_roformer_vocals_fv4_gabox.ckpt': 'gaboxVocalsFv',
    'mel_band_roformer_vocals_fv5_gabox.ckpt': 'gaboxVocalsFv',
    'mel_band_roformer_vocals_fv6_gabox.ckpt': 'gaboxVocalsFv',
    'mel_band_roformer_vocals_fv7b_gabox.ckpt': 'gaboxVocalsFv',
    'mel_band_roformer_vocals_gabox.ckpt': 'gaboxVocals',
    'mel_band_roformer_vocals_v2_gabox.ckpt': 'gaboxVocals',
    'melband_roformer_big_beta4.ckpt': 'bigBeta',
    'melband_roformer_big_beta5e.ckpt': 'bigBeta',
    'melband_roformer_big_beta6.ckpt': 'bigBeta',
    'melband_roformer_big_beta6x.ckpt': 'bigBeta',
    'melband_roformer_inst_v1.ckpt': 'unwaInst',
    'melband_roformer_inst_v1_plus.ckpt': 'unwaInstPlus',
    'melband_roformer_inst_v1e.ckpt': 'unwaInstE',
    'melband_roformer_inst_v1e_plus.ckpt': 'unwaInstE',
    'melband_roformer_inst_v2.ckpt': 'unwaInst',
    'melband_roformer_instvoc_duality_v1.ckpt': 'unwaDuality',
    'melband_roformer_instvox_duality_v2.ckpt': 'unwaDuality',
    'MelBandRoformerBigSYHFTV1.ckpt': 'syhft',
    'MelBandRoformerSYHFT.ckpt': 'syhft',
    'MelBandRoformerSYHFTV2.5.ckpt': 'syhft',
    'MelBandRoformerSYHFTV2.ckpt': 'syhft',
    'MelBandRoformerSYHFTV3Epsilon.ckpt': 'syhft',
    'MGM_HIGHEND_v4.pth': 'vrMgmHigh',
    'MGM_LOWEND_A_v4.pth': 'vrMgmLow',
    'MGM_LOWEND_B_v4.pth': 'vrMgmLow',
    'MGM_MAIN_v4.pth': 'vrMgmMain',
    'model_bs_roformer_ep_317_sdr_12.9755.ckpt': 'viperxBsRoformer',
    'model_bs_roformer_ep_368_sdr_12.9628.ckpt': 'viperxBsRoformer',
    'model_bs_roformer_ep_937_sdr_10.5309.ckpt': 'drumBass',
    'model_chorus_bs_roformer_ep_267_sdr_24.1275.ckpt': 'chorusMaleFemale',
    'model_mel_band_roformer_ep_3005_sdr_11.4360.ckpt': 'viperxMelRoformer',
    'Reverb_HQ_By_FoxJoy.onnx': 'mdxReverb',
    'UVR-BVE-4B_SN-44100-1.pth': 'vrBve',
    'UVR-BVE-4B_SN-44100-2.pth': 'vrBve',
    'UVR-De-Echo-Aggressive.pth': 'vrDeEchoAggressive',
    'UVR-De-Echo-Normal.pth': 'vrDeEcho',
    'UVR-De-Reverb-aufr33-jarredou.pth': 'vrDeReverb',
    'UVR-DeEcho-DeReverb.pth': 'vrDeEchoDeReverb',
    'UVR-DeNoise-Lite.pth': 'vrDeNoiseLite',
    'UVR-DeNoise.pth': 'vrDeNoise',
    'UVR-MDX-NET-Inst_1.onnx': 'mdxInstEarly',
    'UVR-MDX-NET-Inst_2.onnx': 'mdxInstEarly',
    'UVR-MDX-NET-Inst_3.onnx': 'mdxInstEarly',
    'UVR-MDX-NET-Inst_HQ_1.onnx': 'mdxInstHq',
    'UVR-MDX-NET-Inst_HQ_2.onnx': 'mdxInstHq',
    'UVR-MDX-NET-Inst_HQ_3.onnx': 'mdxInstHq',
    'UVR-MDX-NET-Inst_HQ_4.onnx': 'mdxInstHq',
    'UVR-MDX-NET-Inst_HQ_5.onnx': 'mdxInstHq',
    'UVR-MDX-NET-Inst_Main.onnx': 'mdxInstEarly',
    'UVR-MDX-NET-Voc_FT.onnx': 'mdxVocFt',
    'UVR-MDX-NET_Crowd_HQ_1.onnx': 'crowd',
    'UVR_MDXNET_1_9703.onnx': 'mdxVocalEarly',
    'UVR_MDXNET_2_9682.onnx': 'mdxVocalEarly',
    'UVR_MDXNET_3_9662.onnx': 'mdxVocalEarly',
    'UVR_MDXNET_9482.onnx': 'mdxVocalEarly',
    'UVR_MDXNET_KARA.onnx': 'mdxKaraoke',
    'UVR_MDXNET_KARA_2.onnx': 'mdxKaraoke',
    'UVR_MDXNET_Main.onnx': 'mdxVocalEarly',
    'vocals_mel_band_roformer.ckpt': 'kimVocals',
};

// 一覧に出力の名前が無いモデルの出力 (配布元の各モデルの設定ファイルにある名前)
export const SEPARATOR_MODEL_OUTPUTS: Record<string, string[]> = {
    'BS-Roformer-SW.ckpt': ['bass', 'drums', 'other', 'vocals', 'guitar', 'piano'],
    'bs_roformer_instrumental_resurrection_gabox.ckpt': ['vocals', 'other'],
    'bs_roformer_instrumental_resurrection_unwa.ckpt': ['vocals', 'other'],
    'bs_roformer_karaoke_anvuew.ckpt': ['vocals', 'instrumental'],
    'bs_roformer_karaoke_frazer_becruily.ckpt': ['vocals', 'instrumental'],
    'bs_roformer_male_female_by_aufr33_sdr_7.2889.ckpt': ['male', 'female'],
    'bs_roformer_vocals_gabox.ckpt': ['vocals', 'instrumental'],
    'bs_roformer_vocals_resurrection_unwa.ckpt': ['vocals', 'other'],
    'bs_roformer_vocals_revive_unwa.ckpt': ['vocals', 'other'],
    'bs_roformer_vocals_revive_v2_unwa.ckpt': ['vocals', 'other'],
    'bs_roformer_vocals_revive_v3e_unwa.ckpt': ['vocals', 'other'],
    'dereverb_big_mbr_ep_362.ckpt': ['dry', 'other'],
    'dereverb_echo_mbr_fused.ckpt': ['dry', 'other'],
    'dereverb_mel_band_roformer_mono_anvuew.ckpt': ['noreverb', 'reverb'],
    'dereverb_super_big_mbr_ep_346.ckpt': ['dry', 'other'],
    'mel_band_roformer_denoise_debleed_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_2_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_3_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_becruily.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_bleedless_v1_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_bleedless_v2_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_bleedless_v3_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_fullness_noise_v4_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_fullness_v1_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_fullness_v2_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_fullness_v3_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_fullness_v4_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_fv7z_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_fv8_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_fv8b_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_fvx_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_instv5_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_instv5n_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_instv6_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_instv6n_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_instv7_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_instv7n_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_instv8_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_instrumental_instv8n_gabox.ckpt': ['instrumental', 'vocals'],
    'mel_band_roformer_karaoke_becruily.ckpt': ['vocals', 'instrumental'],
    'mel_band_roformer_karaoke_gabox.ckpt': ['vocals', 'instrumental'],
    'mel_band_roformer_karaoke_gabox_v2.ckpt': ['vocals', 'instrumental'],
    'mel_band_roformer_kim_ft2_bleedless_unwa.ckpt': ['vocals', 'other'],
    'mel_band_roformer_kim_ft2_unwa.ckpt': ['vocals', 'other'],
    'mel_band_roformer_kim_ft3_unwa.ckpt': ['vocals', 'other'],
    'mel_band_roformer_vocal_fullness_aname.ckpt': ['vocals', 'other'],
    'mel_band_roformer_vocals_becruily.ckpt': ['vocals', 'other'],
    'mel_band_roformer_vocals_fv1_gabox.ckpt': ['vocals', 'instrumental'],
    'mel_band_roformer_vocals_fv2_gabox.ckpt': ['vocals', 'instrumental'],
    'mel_band_roformer_vocals_fv3_gabox.ckpt': ['vocals', 'instrumental'],
    'mel_band_roformer_vocals_fv4_gabox.ckpt': ['vocals', 'instrumental'],
    'mel_band_roformer_vocals_fv5_gabox.ckpt': ['vocals', 'instrumental'],
    'mel_band_roformer_vocals_fv6_gabox.ckpt': ['vocals', 'instrumental'],
    'mel_band_roformer_vocals_fv7b_gabox.ckpt': ['vocals', 'instrumental'],
    'mel_band_roformer_vocals_gabox.ckpt': ['vocals', 'instrumental'],
    'mel_band_roformer_vocals_v2_gabox.ckpt': ['vocals', 'instrumental'],
    'melband_roformer_big_beta6.ckpt': ['vocals', 'other'],
    'melband_roformer_big_beta6x.ckpt': ['vocals', 'other'],
    'melband_roformer_inst_v1_plus.ckpt': ['other', 'vocals'],
    'melband_roformer_inst_v1e_plus.ckpt': ['other', 'vocals'],
};

// 方式の表示名
export const SEPARATOR_ARCH_LABELS: Record<SeparationArch, string> = {
    MDX: 'MDX-Net',
    VR: 'VR Arch',
    Demucs: 'Demucs',
    MDXC: 'MDXC (Roformer)',
};

export function separatorFilename(item: LibraryItem): string {
    return item.id.slice(SEPARATOR_MODEL_PREFIX.length);
}

// 分離モデルの概要の翻訳キー (概要が無ければ undefined)
export function separatorNoteKey(item: LibraryItem): string | undefined {
    return separatorFileNoteKey(separatorFilename(item));
}

// モデルのファイル名から、分離モデルの概要の翻訳キーを得る (概要が無ければ undefined)
export function separatorFileNoteKey(filename: string): string | undefined {
    const note = SEPARATOR_MODEL_NOTES[filename];
    return note ? `voice.library.separatorModelNotes.${note}` : undefined;
}

// 分離モデルの出力 (一覧に名前が無いモデルは、設定ファイルにある名前)
export function separatorOutputs(item: LibraryItem): string[] {
    return separatorFileOutputs(separatorFilename(item), item.separator?.stems ?? []);
}

export function separatorFileOutputs(filename: string, stems: string[]): string[] {
    return stems.length > 0 ? stems : (SEPARATOR_MODEL_OUTPUTS[filename] ?? []);
}
